version: '3.8'
services:
  hrisdb:
    container_name: hrisdb-drizzle
    image: postgres:15
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  postgres:
